Kalei/api working branch
macrocosm-os/prompting pull request #469
Opened 2024-11-27 20:22 UTC by bkb2135

2024-11-28 04:48 UTC, dbobrenko requested changes
Make sure to remove API keys from the PR

2024-11-28 04:48 UTC, dbobrenko commented on prompting/api/gpt_endpoints/api.py
> +    # return response
```suggestion
```

2024-11-28 04:48 UTC, dbobrenko commented on api_keys.json
> +{"0566dbe21ee33bba9419549716cd6f1f": {"rate_limit": 10, "usage": 0}, "e03da67439c0b7e7a622dde4fa3cf857": {"rate_limit": 10, "usage": 0}}
Make sure to remove this
```suggestion
{}
```

2024-12-02 10:53 UTC, Hollyqui approved these changes
LGTM

2024-12-02 11:41 UTC, merged